<Project>
  <PropertyGroup>
    <CultLibRoot Condition="'$(CultLibRoot)' == '' and '$(CULTLIB_ROOT)' != ''">$(CULTLIB_ROOT)</CultLibRoot>
    <CultLibRoot Condition="'$(CultLibRoot)' == ''">$(MSBuildThisFileDirectory)..\CultLib</CultLibRoot>
    <CultLibRevision>a0813c6eed24d30bf88073ef615b633c77ebfcd6</CultLibRevision>
    <GitExecutable Condition="'$(GitExecutable)' == '' and Exists('C:\Program Files\Git\cmd\git.exe')">C:\Program Files\Git\cmd\git.exe</GitExecutable>
    <GitExecutable Condition="'$(GitExecutable)' == ''">git</GitExecutable>
  </PropertyGroup>
</Project>
