<Project>
  <PropertyGroup>
    <CultLibRoot Condition="'$(CultLibRoot)' == '' and '$(CULTLIB_ROOT)' != ''">$(CULTLIB_ROOT)</CultLibRoot>
    <CultLibRoot Condition="'$(CultLibRoot)' == ''">$(MSBuildThisFileDirectory)..\CultLib</CultLibRoot>
    <CultLibRevision>0f2c1f04ef66a8b85c507747c508960ff1417ae0</CultLibRevision>
    <GitExecutable Condition="'$(GitExecutable)' == '' and Exists('C:\Program Files\Git\cmd\git.exe')">C:\Program Files\Git\cmd\git.exe</GitExecutable>
    <GitExecutable Condition="'$(GitExecutable)' == ''">git</GitExecutable>
  </PropertyGroup>
</Project>
