$ErrorActionPreference = "Stop"

$repoRoot = Resolve-Path (Join-Path $PSScriptRoot "..\..")
Set-Location $repoRoot

function Read-Text([string] $path) {
    return [System.IO.File]::ReadAllText((Join-Path $repoRoot $path))
}

function Assert-Contains([string] $text, [string] $needle, [string] $message) {
    if (-not $text.Contains($needle)) {
        throw $message
    }
}

function Assert-NotContains([string] $text, [string] $needle, [string] $message) {
    if ($text.Contains($needle)) {
        throw $message
    }
}

function Assert-NotMatches([string] $text, [string] $pattern, [string] $message) {
    if ([regex]::IsMatch($text, $pattern)) {
        throw $message
    }
}

$mainMenu = Read-Text "Assets\Scripts\UI\MainMenu.cs"
Assert-Contains $mainMenu "SetRuntimeInputScreenShell(Func<bool> canOpenRuntimeInputScreen, Action openRuntimeInputScreen)" "MainMenu must receive runtime input-screen handoff explicitly."
Assert-Contains $mainMenu "_canOpenRuntimeInputScreen?.Invoke() == true" "MainMenu must query runtime input-screen availability through injected shell."
Assert-Contains $mainMenu "_openRuntimeInputScreen?.Invoke();" "MainMenu must open runtime input screen through injected shell."
Assert-Contains $mainMenu "LatestSectorMap" "MainMenu observed-game boot must read typed sector-map state."
Assert-Contains $mainMenu ".SectorMapAsync()" "MainMenu observed-game boot must use the typed sector-map facade."
Assert-NotContains $mainMenu "LatestDaemonFrame" "MainMenu must not read whole daemon frames for observed-game boot."
Assert-NotContains $mainMenu "LatestAuthoritativeRunFrameAsync" "MainMenu must not read whole daemon frames for observed-game boot."
Assert-NotContains $mainMenu "ActionGameManager.Instance.ShowInputScreenFromMenu" "MainMenu must not open runtime input screen through ActionGameManager.Instance."
Assert-NotContains $mainMenu "ActionGameManager.Instance.CanShowInputScreenFromMenu" "MainMenu must not query runtime input screen through ActionGameManager.Instance."

$mapRenderer = Read-Text "Assets\Scripts\UI\Menu\MapRenderer.cs"
Assert-Contains $mapRenderer "ObjectsViewportAsync" "MapRenderer must exercise the split objects viewport facade."
Assert-Contains $mapRenderer "GravityViewportAsync" "MapRenderer must exercise the split gravity viewport facade."
Assert-Contains $mapRenderer "PlayerSettingsAsync" "MapRenderer must read player settings through AetheriaClient."
Assert-NotContains $mapRenderer "public ActionGameManager" "MapRenderer must not regain an ActionGameManager serialized dependency."
Assert-NotContains $mapRenderer "LatestAuthoritativeRunFrameAsync" "MapRenderer must not regress to whole-frame reads for map viewport data."
Assert-NotContains $mapRenderer "ActionGameManager.RuntimePlayerSettings" "MapRenderer must not read manager-global player settings."

$sectorRenderer = Read-Text "Assets\Scripts\UI\Menu\SectorRenderer.cs"
Assert-Contains $sectorRenderer "AetheriaClient" "SectorRenderer must keep explicit local Verse client ownership."
Assert-Contains $sectorRenderer "CurrentZoneAsync" "SectorRenderer must center from the typed current-zone facade."
Assert-Contains $sectorRenderer "SectorMapAsync" "SectorRenderer zone details must read sector topology through AetheriaClient."
Assert-Contains $sectorRenderer "ZoneDetailsAsync" "SectorRenderer zone details must read daemon zone facts through AetheriaClient."
Assert-Contains $sectorRenderer "OpenRuntimeCatalog" "SectorRenderer zone details must read catalog data through AetheriaClient."
Assert-Contains $sectorRenderer "PlayerSettingsAsync" "SectorRenderer zone details must read formatting settings through AetheriaClient."
Assert-NotContains $sectorRenderer "public ActionGameManager" "SectorRenderer must not regain an ActionGameManager serialized dependency."
Assert-NotContains $sectorRenderer "TryGetObservedRunZone" "SectorRenderer must not ask ActionGameManager for the current zone."
Assert-NotContains $sectorRenderer "ActionGameManager.RuntimeCatalog" "SectorRenderer must not read manager-global runtime catalog."
Assert-NotContains $sectorRenderer "ActionGameManager.RuntimePlayerSettings" "SectorRenderer must not read manager-global player settings."
Assert-NotContains $sectorRenderer "TryGetObservedZoneSnapshot" "SectorRenderer zone details must not ask ActionGameManager for daemon zone snapshots."
Assert-NotContains $sectorRenderer "LatestAuthoritativeRunFrameAsync" "SectorRenderer zone details must not read whole daemon frames."

$sectorMap = Read-Text "Assets\Scripts\UI\Menu\SectorMap.cs"
Assert-Contains $sectorMap "SectorMapAsync" "SectorMap must render from the typed sector-map projection."
Assert-Contains $sectorMap "Subject<int>" "SectorMap clicks must expose typed zone indices, not Unity GalaxyZone objects."
Assert-NotContains $sectorMap "TryGetObservedGalaxy" "SectorMap must not ask ActionGameManager for observed galaxy state."
Assert-NotContains $sectorMap "GalaxyZone" "SectorMap must not retain the legacy GalaxyZone graph."
Assert-NotContains $sectorMap "Dictionary<Faction" "SectorMap must not retain legacy Faction graph materials."

$inventoryPanel = Read-Text "Assets\Scripts\UI\Menu\InventoryPanel.cs"
Assert-Contains $inventoryPanel ".Aetheria()" "InventoryPanel current-subject UI must enter state through the semantic Aetheria facade."
Assert-Contains $inventoryPanel ".Current" "InventoryPanel current-subject UI must read the current-state facade."
Assert-Contains $inventoryPanel ".Entity" "InventoryPanel current-subject UI must read the typed current-entity document handle."
Assert-Contains $inventoryPanel ".LatestAsync()" "InventoryPanel current-subject UI must read a typed current-entity snapshot."
Assert-NotContains $inventoryPanel ".CurrentEntityAsync()" "InventoryPanel current-subject UI must not use the transitional current-entity helper."
Assert-Contains $inventoryPanel "CurrentDockingAsync" "InventoryPanel dropdown docking access must read the typed current-docking facade."
Assert-Contains $inventoryPanel "StationRefitAsync" "InventoryPanel dropdown entity options must read the typed station-refit facade."
Assert-Contains $inventoryPanel "LoadoutRestoreOptions" "InventoryPanel loadout dropdown must read typed station-refit restore options."
Assert-Contains $inventoryPanel "LoadoutTemplateAsync(targetEntityKey)" "InventoryPanel loadout saves must project the target entity through the typed client."
Assert-Contains $inventoryPanel "AetheriaRuntimeStationLoadoutRestoreOption" "InventoryPanel loadout restore submission must use typed station-refit option rows."
Assert-Contains $inventoryPanel "TryGetTypedCurrentDockingBayFacade" "InventoryPanel dropdown docking access must be typed-key validated."
Assert-Contains $inventoryPanel "selection.EntityKey" "InventoryPanel dropdown selections must carry typed entity keys."
Assert-Contains $inventoryPanel "_displayedEntityKey" "InventoryPanel displayed entity state must cache typed entity identity."
Assert-Contains $inventoryPanel "_displayedCargoEntityKey" "InventoryPanel displayed cargo state must cache typed cargo identity."
Assert-Contains $inventoryPanel "TryResolveStationRefitEntity(string entityKey" "InventoryPanel station-refit selection must resolve from typed entity keys."
Assert-NotContains $inventoryPanel "LoadoutTemplatesAsync()" "InventoryPanel must not enumerate loadout templates separately from StationRefitAsync."
Assert-NotContains $inventoryPanel "TryResolveLoadoutTemplatePrice" "InventoryPanel must not price loadout restore options locally."
Assert-NotContains $inventoryPanel "TryResolveCurrentDockingTargetEntityKey" "InventoryPanel must submit the daemon target key from the typed restore option row."
Assert-NotContains $inventoryPanel "TryGetObservedCurrentEntity" "InventoryPanel must not ask ActionGameManager for current-entity identity."
Assert-NotContains $inventoryPanel "ObservedLoadoutTemplates" "InventoryPanel must not ask ActionGameManager for loadout templates."
Assert-NotContains $inventoryPanel "CreateEntityConstructionBlueprint" "InventoryPanel loadout restore validity must not depend on Unity construction blueprints."
Assert-NotContains $inventoryPanel "DockedEntity" "InventoryPanel must not target loadout restore through ActionGameManager.DockedEntity."
Assert-NotMatches $inventoryPanel "ExecuteDropdownSelection[\s\S]*?TryGetObservedDockingBay[\s\S]*?private void HideDropdownSurface" "InventoryPanel dropdown selection must not read manager docking-bay identity directly."
Assert-NotMatches $inventoryPanel "private AetheriaRuntimeInventoryDropdownSurfaceProjection ProjectDropdownSurface\(\)[\s\S]*?TryGetObservedDockingBay[\s\S]*?private void Update" "InventoryPanel dropdown projection must not read manager docking-bay identity directly."
Assert-NotMatches $inventoryPanel "private AetheriaRuntimeInventoryDropdownSurfaceProjection ProjectDropdownSurface\(\)[\s\S]*?TryGetTypedCurrentDockingBayFacade[\s\S]*?private void Update" "InventoryPanel dropdown projection must use typed docking state, not Unity docking-bay facade objects."
Assert-NotMatches $inventoryPanel "private bool IsDisplayedEntityKey\([^)]*\)[\s\S]*?TryResolveEntityRecordKey[\s\S]*?private bool IsDisplayedCargoBayKey" "InventoryPanel displayed entity checks must use cached typed identity."
Assert-NotMatches $inventoryPanel "private bool IsDisplayedCargoBayKey\([^)]*\)[\s\S]*?TryResolveCargoBay[\s\S]*?private bool TryResolveCargoBay" "InventoryPanel displayed cargo checks must use cached typed identity."
Assert-NotMatches $inventoryPanel "ExecuteDropdownSelection[\s\S]*?ObservedAvailableEntities[\s\S]*?private void HideDropdownSurface" "InventoryPanel dropdown selection must resolve options from typed station-refit keys."
Assert-NotMatches $inventoryPanel "private AetheriaRuntimeInventoryDropdownSurfaceProjection ProjectDropdownSurface\(\)[\s\S]*?ObservedAvailableEntities[\s\S]*?private void Update" "InventoryPanel dropdown projection must use typed station-refit options."

$inventoryDropdownSurface = Read-Text "Packages\org.gamecult.aetheria.state\Runtime\AetheriaRuntimeInventoryDropdownSurfaceBuilder.cs"
Assert-Contains $inventoryDropdownSurface "public string EntityKey { get; }" "Inventory dropdown surface selections must carry typed entity identity."
Assert-Contains $inventoryDropdownSurface "entityKey: entity.EntityKey" "Inventory dropdown surface builder must copy typed entity identity into selections."

$inventoryMenu = Read-Text "Assets\Scripts\UI\Menu\InventoryMenu.cs"
Assert-Contains $inventoryMenu ".Aetheria()" "InventoryMenu ship-settings commands must enter state through the semantic Aetheria facade."
Assert-Contains $inventoryMenu ".Current" "InventoryMenu ship-settings commands must read the current-state facade."
Assert-Contains $inventoryMenu ".Entity" "InventoryMenu ship-settings commands must read the typed current-entity document handle."
Assert-Contains $inventoryMenu ".LatestAsync()" "InventoryMenu ship-settings commands must read a typed current-entity snapshot."
Assert-NotContains $inventoryMenu ".CurrentEntityAsync()" "InventoryMenu ship-settings commands must not use the transitional current-entity helper."
Assert-Contains $inventoryMenu "TryResolveCurrentEntityDocument" "InventoryMenu ship-settings state must read the typed current-entity document."
Assert-Contains $inventoryMenu "_shipSettingsCurrentEntity" "InventoryMenu ship-settings surface must retain typed current-entity state."
Assert-Contains $inventoryMenu "latestCurrentEntity.ShutdownPerformance" "InventoryMenu ship-settings surface must use typed shutdown-performance projection."
Assert-Contains $inventoryMenu "TryGetTypedCurrentEntityFacade" "InventoryMenu current facade access must be typed-key validated."
Assert-Contains $inventoryMenu "SetObservedFacadeIndex(AetheriaUnityObservedFacadeIndex observedFacadeIndex)" "InventoryMenu must receive facade adaptation explicitly."
Assert-Contains $inventoryMenu "_observedFacadeIndex.TryResolveEntityByRecordKey" "InventoryMenu must adapt current entity facades by typed daemon record key."
Assert-Contains $inventoryMenu "CurrentDockingAsync" "InventoryMenu docking facade access must read the typed current-docking facade."
Assert-Contains $inventoryMenu "TryGetTypedCurrentDockingBayFacade" "InventoryMenu docking facade access must be typed-key validated."
Assert-Contains $inventoryMenu "ResolveDefaultShutdownPerformance()" "InventoryMenu ship-settings reset must use typed runtime policy for the default threshold."
Assert-Contains $inventoryMenu "ResolvePlayerSettings()?.DefaultShutdownPerformance" "InventoryMenu must read default shutdown performance from typed player settings."
Assert-NotContains $inventoryMenu "TryGetObservedCurrentEntity(" "InventoryMenu must not read broad manager-global current entity state."
Assert-NotContains $inventoryMenu "entity.Settings.ShutdownPerformance" "InventoryMenu ship-settings surface must not read shutdown threshold from a Unity entity facade."
Assert-NotContains $inventoryMenu "_shipSettingsEntity" "InventoryMenu ship-settings surface must not store Unity entity facade state."
Assert-NotContains $inventoryMenu "GameManager.Settings.GameplaySettings.DefaultShutdownPerformance" "InventoryMenu must not read shutdown defaults from Unity GameSettings."
Assert-NotMatches $inventoryMenu "OnEnable\(\)[\s\S]*?TryGetObservedCurrentEntity[\s\S]*?private void OnDisable" "InventoryMenu OnEnable must not read manager current-entity identity directly."
Assert-NotMatches $inventoryMenu "OnBackgroundClick[\s\S]*?TryGetObservedCurrentEntity[\s\S]*?private void RenderCurrentShipSettingsSurface" "InventoryMenu background click must not read manager current-entity identity directly."
Assert-NotMatches $inventoryMenu "HandleCurrentShipSettingsSurfaceCommand[\s\S]*?TryGetObservedCurrentEntity[\s\S]*?private void HideCurrentShipSettingsSurface" "InventoryMenu ship-settings command handler must not ask ActionGameManager for current-entity identity."
Assert-Contains $inventoryPanel "TryResolveTypedInventoryRows" "InventoryPanel cargo/equipment submissions must validate against typed inventory projection rows."
Assert-Contains $inventoryPanel "TryValidateTypedCargoSlot" "InventoryPanel cargo submissions must validate typed cargo slot identity."
Assert-Contains $inventoryPanel "TryValidateTypedEquipmentSlot" "InventoryPanel equipment submissions must validate typed equipment slot identity."
Assert-Contains $inventoryPanel "InventoryAsync(entityIndex)" "InventoryPanel must read non-current inventory through the typed client facade."
Assert-Contains $inventoryPanel "origin.Cargo.TryGetValue(item, out var originPosition)" "InventoryPanel cargo submissions must carry the typed origin grid cell."
Assert-NotContains $inventoryPanel "int.MinValue" "InventoryPanel cargo/equipment submissions must not send unknown origin coordinates."
Assert-NotContains $inventoryPanel "TryResolveObservedCargoBayCommandTarget" "InventoryPanel must not resolve cargo operations through manager command-target adapters."
Assert-NotContains $inventoryPanel "TryResolveObservedEquippedItemCommandTarget" "InventoryPanel must not resolve equipment operations through manager command-target adapters."
Assert-Contains $inventoryMenu "TryResolveTypedInventoryRows" "InventoryMenu cargo/equipment submissions must validate against typed inventory projection rows."
Assert-Contains $inventoryMenu "TryValidateTypedCargoSlot" "InventoryMenu cargo submissions must validate typed cargo slot identity."
Assert-Contains $inventoryMenu "TryValidateTypedEquipmentSlot" "InventoryMenu equipment submissions must validate typed equipment slot identity."
Assert-Contains $inventoryMenu "InventoryAsync(entityIndex)" "InventoryMenu must read non-current inventory through the typed client facade."
Assert-Contains $inventoryMenu "origin.Cargo.TryGetValue(item, out var originPosition)" "InventoryMenu cargo submissions must carry the typed origin grid cell."
Assert-Contains $inventoryMenu "SetActionBarPresentation(AetheriaUnityActionBarPresentation actionBarPresentation)" "InventoryMenu must receive action-bar presentation explicitly."
Assert-NotContains $inventoryMenu "ProjectEquippedItemActionBarSlots(" "InventoryMenu must not project Unity-local action-bar binding controls into the shared equipped-item surface."
Assert-NotContains $inventoryMenu "RequestWeaponGroupActionBarBinding(" "InventoryMenu must not treat shared equipped-item commands as Unity action-bar binding edits."
Assert-NotContains $inventoryMenu "RequestClearActionBarBinding(" "InventoryMenu must not treat shared equipped-item commands as Unity action-bar binding clears."
Assert-NotContains $inventoryMenu "_actionBarPresentation?.RequestWeaponGroupBinding(slotIndex, groupIndex)" "InventoryMenu must not bind Unity action-bar slots from shared equipped-item commands."
Assert-NotContains $inventoryMenu "_actionBarPresentation?.ClearBinding(slotIndex)" "InventoryMenu must not clear Unity action-bar slots from shared equipped-item commands."
Assert-NotContains $inventoryMenu "GameManager.GetActionBarSlotCount" "InventoryMenu must not ask ActionGameManager for action-bar slot count."
Assert-NotContains $inventoryMenu "GameManager.GetActionBarSlotLabel" "InventoryMenu must not ask ActionGameManager for action-bar slot labels."
Assert-NotContains $inventoryMenu "GameManager.GetActionBarBindingLabel" "InventoryMenu must not ask ActionGameManager for action-bar binding labels."
Assert-NotContains $inventoryMenu "GameManager.TryResolveActionBarSlotControlPath" "InventoryMenu must not ask ActionGameManager for action-bar control paths."
Assert-NotContains $inventoryMenu "int.MinValue" "InventoryMenu cargo/equipment submissions must not send unknown origin coordinates."
Assert-NotContains $inventoryMenu "TryResolveObservedCargoBayCommandTarget" "InventoryMenu must not resolve cargo operations through manager command-target adapters."
Assert-NotContains $inventoryMenu "TryResolveObservedEquippedItemCommandTarget" "InventoryMenu must not resolve equipment operations through manager command-target adapters."

$tradeMenu = Read-Text "Assets\Scripts\UI\Menu\TradeMenu.cs"
Assert-Contains $tradeMenu "CurrentDockingAsync" "TradeMenu docking and docked-ship purchase access must read the typed current-docking facade."
Assert-Contains $tradeMenu "StationRefitAsync" "TradeMenu cargo selector ship options must read the typed station-refit facade."
Assert-Contains $tradeMenu "ResolveStationRefit()?.Credits" "TradeMenu credits must read from the typed station-refit projection."
Assert-Contains $tradeMenu "BuildStationStockRows" "TradeMenu row list must be built from typed station stock."
Assert-Contains $tradeMenu "ResolveStationRefit()?.StationStock" "TradeMenu station stock rows must read from the typed station-refit projection."
Assert-Contains $tradeMenu "var sourcePosition = new int2(row.Stock.X, row.Stock.Y)" "TradeMenu trade purchase source position must come from typed station stock."
Assert-Contains $tradeMenu "TryResolveCurrentDockingTargetEntityKey" "TradeMenu docked-ship purchase target must resolve from typed current docking."
Assert-Contains $tradeMenu "SetTargetCargo" "TradeMenu target cargo selection must store typed entity key and cargo index."
Assert-Contains $tradeMenu "OwnedQuantity" "TradeMenu owned counts must read typed station stock ownership facts."
Assert-Contains $tradeMenu "CargoTargets" "TradeMenu target cargo rows must come from typed station-refit cargo targets."
Assert-Contains $tradeMenu "AetheriaRuntimeStationCargoTargetRow" "TradeMenu cargo selector must use typed station-refit cargo target rows."
Assert-NotContains $tradeMenu "ResolveStationStockAdapter" "TradeMenu station stock rows must not adapt Unity cargo items for typed stock display."
Assert-NotContains $tradeMenu "Inventory.Cargo.Keys" "TradeMenu station stock display must not enumerate Unity cargo keys."
Assert-NotContains $tradeMenu "TryGetTypedCurrentDockingBayFacade" "TradeMenu target cargo selection must not adapt Unity docking bay objects."
Assert-NotContains $tradeMenu "TryResolveCargoBay" "TradeMenu purchase target cargo must not resolve through Unity cargo objects."
Assert-NotContains $tradeMenu "TryResolveObservedAvailableEntityByKey" "TradeMenu cargo selector must not resolve typed station-refit options through Unity observed entities."
Assert-NotContains $tradeMenu "_cargoSelectorStationRefitEntities" "TradeMenu cargo selector must not reconstruct target rows from available entity options."
Assert-NotContains $tradeMenu "ObservedAvailableEntities" "TradeMenu cargo selector must not enumerate Unity observed entities."
Assert-NotContains $tradeMenu "TryGetObservedDockingBay" "TradeMenu cargo selector must not read manager docking-bay identity."
Assert-NotContains $tradeMenu "TryResolveObservedCargoBayCommandTarget" "TradeMenu purchase target cargo must not resolve through manager cargo adapters."
Assert-NotContains $tradeMenu "ItemsOfType" "TradeMenu owned counts must not read Unity cargo item dictionaries."
Assert-NotContains $tradeMenu "CountAvailablePlayerShips" "TradeMenu must not compute owned ship counts locally."
Assert-NotContains $tradeMenu "CountTargetCargoItems" "TradeMenu must not compute owned cargo counts locally."
Assert-NotContains $tradeMenu "CargoBays.Count" "TradeMenu cargo selector must not use Unity ship cargo bay counts."
Assert-NotContains $tradeMenu "DockedEntity" "TradeMenu must not target purchases through ActionGameManager.DockedEntity."
Assert-NotContains $tradeMenu "GameManager.Credits" "TradeMenu must not read manager-global credits."
Assert-NotContains $tradeMenu "stationInventory" "TradeMenu must not recover station purchase source through Unity inventory."
Assert-NotMatches $tradeMenu "void Populate\(\)[\s\S]*?Inventory\.Cargo\.Keys[\s\S]*?private IEnumerable<TradeRow> BuildStationStockRows" "TradeMenu Populate must not enumerate Unity cargo as station stock truth."
Assert-NotMatches $tradeMenu "RequestTradePurchase\([\s\S]*?Cargo\.TryGetValue[\s\S]*?private bool TryResolveCargoBay" "TradeMenu trade purchase command source must not come from Unity cargo lookup."
Assert-NotMatches $tradeMenu "OnEnable\(\)[\s\S]*?TryGetObservedDockingBay[\s\S]*?void Populate" "TradeMenu OnEnable must not read manager docking-bay identity directly."
Assert-NotMatches $tradeMenu "ProjectTradeCargoSelectorSurface[\s\S]*?TryGetObservedDockingBay[\s\S]*?private void ApplyCargoSelection" "TradeMenu cargo selector projection must not read manager docking-bay identity directly."
Assert-NotMatches $tradeMenu "ApplyCargoSelection[\s\S]*?TryGetObservedDockingBay[\s\S]*?private void SetTargetCargo" "TradeMenu cargo selector selection must not read manager docking-bay identity directly."
Assert-NotMatches $tradeMenu "ProjectTradeCargoSelectorSurface[\s\S]*?ObservedAvailableEntities[\s\S]*?private void ApplyCargoSelection" "TradeMenu cargo selector projection must use typed station-refit options."
Assert-NotMatches $tradeMenu "ApplyCargoSelection[\s\S]*?ObservedAvailableEntities[\s\S]*?private void SetTargetCargo" "TradeMenu cargo selector selection must resolve options from typed station-refit keys."
Assert-NotMatches $tradeMenu "private int CountAvailablePlayerShips\([^)]*\)\s*\{[\s\S]*?ObservedAvailableEntities[\s\S]*?\n    \}" "TradeMenu available-ship counts must come from typed station-refit state."
Assert-NotContains $tradeMenu "HullItemKey" "TradeMenu owned ship counts must come from station stock facts, not UI-side hull comparisons."

$inventoryPanel = Read-Text "Assets\Scripts\UI\Menu\InventoryPanel.cs"
Assert-Contains $inventoryPanel "StationRefitAsync()" "InventoryPanel must resolve station/refit selections from typed station-refit projection."
Assert-Contains $inventoryPanel "SetObservedFacadeIndex(AetheriaUnityObservedFacadeIndex observedFacadeIndex)" "InventoryPanel must receive facade adaptation explicitly."
Assert-Contains $inventoryPanel "_observedFacadeIndex.TryResolveEntityByRecordKey" "InventoryPanel may adapt Unity facade objects only by typed daemon record key."
Assert-Contains $inventoryPanel "_observedFacadeIndex.TryResolveDockingBayByRecordKey" "InventoryPanel must adapt docking bays by typed daemon parent key and docking bay index."
Assert-NotContains $inventoryPanel "ObservedAvailableEntities()" "InventoryPanel must not read broad manager-global available entity collections."
Assert-NotContains $inventoryPanel "TryGetObservedDockingBay(" "InventoryPanel must read typed current docking before adapting a Unity docking bay facade."

$inventoryMenu = Read-Text "Assets\Scripts\UI\Menu\InventoryMenu.cs"
Assert-Contains $inventoryMenu "CurrentDockingAsync()" "InventoryMenu must resolve docking display state from typed current-docking projection."
Assert-Contains $inventoryMenu "_observedFacadeIndex.TryResolveDockingBayByRecordKey" "InventoryMenu must adapt docking bays by typed daemon parent key and docking bay index."
Assert-NotContains $inventoryMenu "TryGetObservedDockingBay(" "InventoryMenu must not read broad manager-global docking bay state."

$localMenu = Read-Text "Assets\Scripts\UI\Menu\LocalMenu.cs"
Assert-Contains $localMenu "TryResolveDockedLocalStory(out _currentLocation)" "LocalMenu must resolve local story visibility through its typed docking path."
Assert-Contains $localMenu "CurrentDockingAsync()" "LocalMenu must read typed current-docking state before showing local story."
Assert-Contains $localMenu "SetObservedFacadeIndex(AetheriaUnityObservedFacadeIndex observedFacadeIndex)" "LocalMenu must receive facade adaptation explicitly."
Assert-Contains $localMenu "_observedFacadeIndex.TryResolveDockingBayByRecordKey" "LocalMenu may adapt story-bearing docking parents only by typed parent key and docking bay index."
Assert-Contains $localMenu "docking.DockParentEntityKey" "LocalMenu must use typed dock parent identity for local story adaptation."
Assert-Contains $localMenu "docking.DockingBayIndex" "LocalMenu must use typed docking bay index for local story adaptation."
Assert-NotContains $localMenu "TryGetObservedDockedLocalStory" "LocalMenu must not ask ActionGameManager for docked local story state."
Assert-NotContains $localMenu "DockedEntity" "LocalMenu must not read ActionGameManager.DockedEntity."

$confirmationDialog = Read-Text "Assets\Scripts\UI\ConfirmationDialog.cs"
Assert-Contains $confirmationDialog "public void SetInputGate(Action enableGlobalInput, Action disableGlobalInput)" "ConfirmationDialog must receive input gating explicitly."
Assert-NotContains $confirmationDialog "ActionGameManager.Instance" "ConfirmationDialog must not reach through ActionGameManager.Instance for input gating."

$schematicDisplay = Read-Text "Assets\Scripts\UI\HUD\SchematicDisplay.cs"
Assert-Contains $schematicDisplay "public void SetRenderSettings(AetheriaRuntimeDaemonRenderSettings renderSettings)" "SchematicDisplay must receive HUD render settings explicitly."
Assert-Contains $schematicDisplay "_renderSettings?.NormalizeThermalRisk(" "SchematicDisplay must normalize thermal risk through injected daemon render settings."
Assert-Contains $schematicDisplay "private AetheriaRuntimeCurrentEntityDocument _currentEntityDocument;" "SchematicDisplay must cache the typed current-entity HUD document."
Assert-Contains $schematicDisplay "ResolveCurrentEntityHudStatus()" "SchematicDisplay must read player HUD facts from typed current-entity state."
Assert-Contains $schematicDisplay ".Aetheria()" "SchematicDisplay must enter current entity HUD state through the semantic Aetheria facade."
Assert-Contains $schematicDisplay ".Current" "SchematicDisplay must read current entity HUD state from the current-state facade."
Assert-Contains $schematicDisplay ".Entity" "SchematicDisplay must read current entity HUD state from the typed entity document handle."
Assert-Contains $schematicDisplay ".LatestAsync()" "SchematicDisplay must read current entity HUD status through a typed document handle."
Assert-NotContains $schematicDisplay ".CurrentEntityAsync()" "SchematicDisplay must not use the transitional current-entity helper."
Assert-Contains $schematicDisplay "hud.OverrideShutdown" "SchematicDisplay must render override shutdown from typed HUD state."
Assert-Contains $schematicDisplay "hud.HeatsinksEnabled" "SchematicDisplay must render heatsink status from typed HUD state."
Assert-Contains $schematicDisplay "hud.Heatstroke" "SchematicDisplay must render heatstroke from typed HUD state."
Assert-Contains $schematicDisplay "hud.Hypothermia" "SchematicDisplay must render hypothermia from typed HUD state."
Assert-Contains $schematicDisplay "hud.Visibility" "SchematicDisplay must render player visibility from typed HUD state."
Assert-NotContains $schematicDisplay "_entity.OverrideShutdown" "SchematicDisplay player HUD must not read override shutdown from the Unity entity facade."
Assert-NotContains $schematicDisplay "_entity.HeatsinksEnabled" "SchematicDisplay player HUD must not read heatsink status from the Unity entity facade."
Assert-NotContains $schematicDisplay "_entity.Heatstroke" "SchematicDisplay player HUD must not read heatstroke from the Unity entity facade."
Assert-NotContains $schematicDisplay "_entity.Hypothermia" "SchematicDisplay player HUD must not read hypothermia from the Unity entity facade."
Assert-NotContains $schematicDisplay "ActionGameManager.Instance.ZoneRenderer" "SchematicDisplay must not reach through ActionGameManager.Instance.ZoneRenderer."

$actionGameManager = Read-Text "Assets\Scripts\Gameplay\ActionGameManager.cs"
$observedFrameApplier = Read-Text "Assets\Scripts\Gameplay\AetheriaUnityObservedFrameApplier.cs"
$observedTargetQuery = Read-Text "Assets\Scripts\Gameplay\AetheriaUnityObservedTargetQuery.cs"
$targetPresentation = Read-Text "Assets\Scripts\Gameplay\AetheriaUnityTargetPresentation.cs"
$observedDockingIndex = Read-Text "Assets\Scripts\Gameplay\AetheriaUnityObservedDockingIndex.cs"
$currentEntityBinder = Read-Text "Assets\Scripts\Gameplay\AetheriaUnityCurrentEntityBinder.cs"
$currentEntityPresentation = Read-Text "Assets\Scripts\Gameplay\AetheriaUnityCurrentEntityPresentation.cs"
$menuShell = Read-Text "Assets\Scripts\Gameplay\AetheriaUnityMenuShell.cs"
$gameplayInputShell = Read-Text "Assets\Scripts\Gameplay\AetheriaUnityGameplayInputShell.cs"
$runtimeClientProvider = Read-Text "Assets\Scripts\Gameplay\AetheriaUnityRuntimeClientProvider.cs"
$renderSettingsBridge = Read-Text "Assets\Scripts\Gameplay\AetheriaUnityRenderSettingsBridge.cs"
$cockpitHudShell = Read-Text "Assets\Scripts\Gameplay\AetheriaUnityCockpitHudShell.cs"
$gameplayBootShell = Read-Text "Assets\Scripts\Gameplay\AetheriaUnityGameplayBootShell.cs"
$sceneWiring = Read-Text "Assets\Scripts\Gameplay\AetheriaUnityGameplaySceneWiring.cs"
Assert-Contains $actionGameManager "private readonly AetheriaUnityObservedFacadeIndex _observedFacadeIndex" "ActionGameManager must keep observed facade adaptation behind an explicit helper."
Assert-Contains $actionGameManager "private AetheriaUnityGameplaySceneWiring SceneWiring =>" "ActionGameManager should delegate Unity scene dependency wiring to a focused helper."
Assert-Contains $actionGameManager "SceneWiring.ConfigureObservedFacadeIndex(_observedFacadeIndex)" "ActionGameManager should delegate facade injection to scene wiring."
Assert-Contains $sceneWiring "public sealed class AetheriaUnityGameplaySceneWiring" "Unity scene wiring should live outside ActionGameManager."
Assert-Contains $sceneWiring "Inventory?.SetObservedFacadeIndex(observedFacadeIndex)" "Scene wiring should inject facade adaptation into InventoryMenu."
Assert-NotContains $actionGameManager "public bool TryResolveObservedEntityRecordKey" "ActionGameManager must not expose facade record-key lookup as public manager API."
Assert-NotContains $actionGameManager "public bool TryResolveObservedEntityFacadeByRecordKey" "ActionGameManager must not expose entity facade lookup as public manager API."
Assert-NotContains $actionGameManager "public bool TryResolveObservedDockingBayFacadeByRecordKey" "ActionGameManager must not expose docking facade lookup as public manager API."
Assert-Contains $actionGameManager "var boot = GameplayBootShell.Boot();" "ActionGameManager should delegate runtime boot/catalog setup to the gameplay boot shell."
Assert-Contains $actionGameManager "SceneWiring.ConfigureCurrentEntityPresentation(_currentEntityPresentation, boot.RuntimeCatalog);" "ActionGameManager should delegate boot catalog injection into current-entity presentation."
Assert-Contains $actionGameManager "SceneWiring.ConfigureTargetPresentation(" "ActionGameManager should delegate boot catalog injection into target presentation."
Assert-Contains $actionGameManager "() => ResolveDaemonObserver()?.Client" "ActionGameManager should give target queries the typed local client, not a raw zone snapshot delegate."
Assert-Contains $sceneWiring "observedFacadeIndex.TryResolveEntityByDaemonIndex" "Scene wiring should adapt target presentation entities through the facade index."
Assert-Contains $actionGameManager "SceneWiring.ConfigureActionBarPresentation(" "ActionGameManager should delegate boot catalog injection into local action-bar presentation."
Assert-NotContains $actionGameManager "private void ConfigureCurrentEntityPresentation(" "ActionGameManager must not own current-entity presentation scene wiring."
Assert-NotContains $actionGameManager "private void ConfigureTargetPresentation(" "ActionGameManager must not own target presentation scene wiring."
Assert-NotContains $actionGameManager "TryGetObservedEntityFacade" "ActionGameManager must not own daemon-index facade lookup shims."
Assert-NotContains $actionGameManager "private void ConfigureActionBarPresentation(" "ActionGameManager must not own action-bar presentation scene wiring."
Assert-NotContains $actionGameManager "private void ConfigureObservedFacadeIndex(" "ActionGameManager must not own facade scene wiring."
Assert-NotContains $actionGameManager "private static AetheriaRuntimeCatalogSnapshot _runtimeCatalog" "ActionGameManager must not cache runtime catalog as manager-global state."
Assert-NotContains $actionGameManager "FindTypedRuntimeItem(" "ActionGameManager must not own runtime catalog item lookup policy."
Assert-NotContains $actionGameManager "ArticulatedWeaponBehaviorKinds" "ActionGameManager must not own weapon presentation policy."
Assert-Contains $actionGameManager "ItemManager = boot.ItemManager;" "ActionGameManager should receive ItemManager from the gameplay boot shell."
Assert-Contains $actionGameManager "_loadoutItemProjector = boot.LoadoutItemProjector;" "ActionGameManager should receive loadout projector from the gameplay boot shell."
Assert-Contains $gameplayBootShell "public sealed class AetheriaUnityGameplayBootShell" "Unity runtime boot/catalog setup should live outside ActionGameManager."
Assert-Contains $gameplayBootShell "AetheriaRuntimeStateBoot.Inspect(AetheriaUnityRuntimePaths.GameDataDirectory)" "Gameplay boot shell should inspect the runtime target."
Assert-Contains $gameplayBootShell "AetheriaUnityRuntimeClientProvider.ResolveClient(stateBoot.StateFilePath, stateBoot.RuntimeId)" "Gameplay boot shell should resolve the typed runtime client with the inspected Verse runtime id."
Assert-Contains $gameplayBootShell "Aetheria runtime id: {stateBoot.RuntimeId}" "Gameplay boot shell should log the inspected Verse runtime id."
Assert-Contains $gameplayBootShell ".OpenRuntimeCatalog()" "Gameplay boot shell should open the typed runtime catalog."
Assert-Contains $gameplayBootShell "new ItemManager(" "Gameplay boot shell should construct the Unity item adapter."
Assert-Contains $gameplayBootShell "new AetheriaUnityLoadoutItemProjector(itemManager, runtimeCatalog)" "Gameplay boot shell should construct the loadout item projector."
Assert-Contains $gameplayBootShell "ZoneRenderer.SetDroppedPickupItemProjector(loadoutItemProjector.CreateLoadoutItem)" "Gameplay boot shell should configure dropped pickup projection."
Assert-Contains $gameplayBootShell "ZoneRenderer.BodySettingsCollections = Settings.BodySettingsCollections" "Gameplay boot shell should configure renderer body settings."
Assert-Contains $gameplayBootShell "AetheriaUnityRenderSettingsBridge.Build(" "Gameplay boot shell should configure daemon render settings."
Assert-Contains $gameplayBootShell "CockpitHudShell.SetRenderSettings(ZoneRenderer.RenderSettings)" "Gameplay boot shell should configure cockpit HUD render settings."
Assert-Contains $gameplayBootShell "AetheriaUnityRuntimeClientProvider.PlayerSettings.GraphicsSettings.ShowAsteroidsInMinimap" "Gameplay boot shell should apply minimap asteroid visibility."
Assert-Contains $gameplayBootShell "public readonly struct AetheriaUnityGameplayBootResult" "Gameplay boot shell should return the Unity adapters needed by scene composition."
Assert-Contains $actionGameManager "UpdatePlayerPanel = () => CockpitHudShell.UpdatePlayer(CurrentEntity)" "ActionGameManager should delegate player HUD refresh to the HUD shell."
Assert-Contains $actionGameManager "UpdateTargetPanel = target => CockpitHudShell.UpdateTarget(target, CurrentEntity)" "ActionGameManager should delegate target HUD refresh to the HUD shell."
Assert-Contains $cockpitHudShell "public sealed class AetheriaUnityCockpitHudShell" "Cockpit HUD presentation should live outside ActionGameManager."
Assert-Contains $cockpitHudShell "public void SetRenderSettings(AetheriaRuntimeDaemonRenderSettings renderSettings)" "Cockpit HUD shell should receive daemon render settings explicitly."
Assert-Contains $cockpitHudShell "SchematicDisplay?.SetRenderSettings(renderSettings)" "Cockpit HUD shell should configure the player HUD schematic."
Assert-Contains $cockpitHudShell "TargetSchematicDisplay?.SetRenderSettings(renderSettings)" "Cockpit HUD shell should configure the target HUD schematic."
Assert-Contains $cockpitHudShell "public void UpdatePlayer(Entity currentEntity)" "Cockpit HUD shell should own player HUD refresh."
Assert-Contains $cockpitHudShell "public void UpdateTarget(Entity target, Entity currentEntity)" "Cockpit HUD shell should own target HUD refresh."
Assert-NotContains $actionGameManager "ConfigureSchematicDisplayRenderSettings()" "ActionGameManager must not own cockpit HUD render setting configuration."
Assert-NotContains $actionGameManager "SchematicDisplay?.SetRenderSettings(" "ActionGameManager must not configure schematic render settings directly."
Assert-NotContains $actionGameManager "TargetSchematicDisplay?.SetRenderSettings(" "ActionGameManager must not configure target schematic render settings directly."
Assert-NotContains $actionGameManager "private void UpdatePlayerPanel()" "ActionGameManager must not own cockpit HUD player refresh."
Assert-NotContains $actionGameManager "private void UpdateTargetPanel(Entity target)" "ActionGameManager must not own cockpit HUD target refresh."
Assert-NotContains $actionGameManager "AetheriaRuntimeStateBoot.Inspect(" "ActionGameManager must not inspect runtime targets directly."
Assert-NotContains $actionGameManager "ResolveClient(stateBoot.StateFilePath).OpenRuntimeCatalog()" "ActionGameManager must not open runtime catalogs directly."
Assert-NotContains $actionGameManager "ItemManager = new ItemManager(" "ActionGameManager must not construct ItemManager directly."
Assert-NotContains $actionGameManager "ZoneRenderer.SetDroppedPickupItemProjector(" "ActionGameManager must not configure renderer pickup projection directly."
Assert-NotContains $actionGameManager "ZoneRenderer.BodySettingsCollections = Settings.BodySettingsCollections" "ActionGameManager must not configure renderer body settings directly."
Assert-Contains $observedFrameApplier "ZoneRenderAsync()" "Unity observed frame application must consume the typed zone-render facade."
Assert-NotContains $observedFrameApplier "ProjectZoneRender(" "Unity observed frame application must not rebuild zone-render feeds from raw frames."
Assert-NotContains $observedFrameApplier "LastObservedState?.Run" "Unity observed frame application must not read the raw observed run for current-zone lookups."
Assert-NotContains $observedFrameApplier "FramePath" "Unity observed frame application should key the presentation cache by typed projection identity, not publication file paths."
Assert-Contains $observedTargetQuery "ZoneContactsAsync()" "Unity target queries must consume the typed zone-contacts facade."
Assert-NotContains $observedTargetQuery "AetheriaRuntimeZoneSnapshotCommit" "Unity target queries must not receive raw zone snapshots."
Assert-NotContains $observedTargetQuery "AetheriaRuntimeDaemonRenderQueries.TryQueryEntityContact" "Unity target queries must not query contacts from raw zone snapshots."
Assert-NotContains $observedTargetQuery "AetheriaRuntimeDaemonRenderQueries.TryQueryEntityTarget" "Unity target queries must not query targets from raw zone snapshots."
Assert-Contains $targetPresentation "ResolveVisibleContacts" "Unity target presentation must receive typed contact rows."
Assert-NotContains $targetPresentation "QueryEntityContacts(" "Unity target presentation must not query contacts from raw zone snapshots."
Assert-NotContains $targetPresentation "ResolveZone" "Unity target presentation must not hold raw zone snapshot access."
Assert-Contains $observedDockingIndex "CurrentDockingAsync()" "Unity docking state must read the typed current-docking facade."
Assert-Contains $observedDockingIndex "TryResolveEntityByRecordKey(docking.DockParentEntityKey" "Unity docking facade adaptation must be keyed by typed dock parent identity."
Assert-NotContains $observedDockingIndex "AetheriaRuntimeZoneSnapshotCommit" "Unity docking state must not receive raw zone snapshots."
Assert-NotContains $observedDockingIndex "TryGetParentSnapshot" "Unity docking state must not scan raw snapshot parent relationships."
Assert-NotContains $observedDockingIndex "TryGetEntitySnapshot" "Unity docking state must not scan raw entity snapshots."
Assert-Contains $currentEntityBinder "ResolveZoneRender?.Invoke()" "Current-entity binding may resolve dock camera context through the typed zone-render feed."
Assert-NotContains $currentEntityBinder "ResolveDaemonZone" "Current-entity binding must not pass raw zone snapshots into docked presentation."
Assert-Contains $currentEntityPresentation "AetheriaRuntimeZoneRenderDocument zoneRender" "Docked presentation must consume the typed zone-render document for body lookups."
Assert-Contains $currentEntityPresentation "AetheriaRuntimeZoneRenderBodyPose" "Docked presentation must resolve body look-at through typed render body poses."
Assert-NotContains $currentEntityPresentation "AetheriaRuntimeZoneSnapshotCommit daemonZone" "Docked presentation must not receive raw zone snapshots."
Assert-Contains $gameplayBootShell "AetheriaUnityRenderSettingsBridge.Build(" "Gameplay boot shell should delegate daemon render-settings lowering to the render settings bridge."
Assert-Contains $renderSettingsBridge "public static class AetheriaUnityRenderSettingsBridge" "Unity render settings lowering should live outside ActionGameManager."
Assert-Contains $renderSettingsBridge "public static AetheriaRuntimeDaemonRenderSettings Build(" "Unity render settings bridge should expose focused render-settings lowering."
Assert-Contains $renderSettingsBridge "new AetheriaRuntimeDaemonRenderSettings(" "Unity render settings bridge should construct the shared daemon render settings."
Assert-Contains $renderSettingsBridge "settings.GameplaySettings.HypothermiaTemperature" "Unity render settings bridge should lower thermal HUD thresholds."
Assert-Contains $renderSettingsBridge "settings.GameplaySettings.HeatstrokeTemperature" "Unity render settings bridge should lower thermal HUD thresholds."
Assert-Contains $renderSettingsBridge "settings.MinimapZoomLevels?.Select(level => (double)level).ToArray()" "Unity render settings bridge should lower minimap zoom levels explicitly."
Assert-Contains $actionGameManager "SceneWiring.ConfigureRuntimeInputScreenShell(MenuShell)" "ActionGameManager should delegate runtime input-screen handoff to scene wiring."
Assert-Contains $sceneWiring "MainMenu?.SetRuntimeInputScreenShell(menuShell.CanOpenRuntimeInputScreen, menuShell.ShowRuntimeInputScreen)" "Scene wiring should inject Unity menu-shell input-screen callbacks into MainMenu."
Assert-Contains $actionGameManager "GameplayInputShell.Bootstrap();" "ActionGameManager should bootstrap Unity gameplay input through the dedicated input shell."
Assert-Contains $menuShell "public bool CanOpenRuntimeInputScreen()" "Unity menu shell should own runtime input-screen availability."
Assert-Contains $menuShell "public void ShowRuntimeInputScreen()" "Unity menu shell should own runtime input-screen opening."
Assert-Contains $gameplayInputShell "public sealed class AetheriaUnityGameplayInputShell" "Unity gameplay input callbacks should live outside ActionGameManager."
Assert-Contains $gameplayInputShell "Input.Global.InputScreen.performed += context => MenuShell.ToggleFullscreenMenu(MenuShell.HelpScreen);" "Gameplay input shell should route the runtime input-screen hotkey through the shared menu shell."
Assert-Contains $gameplayInputShell "Input.Player.TargetNearest.performed += context => PilotOperationAdapter.RequestTargetNearest();" "Gameplay input shell should lower player targeting input through typed pilot operations."
Assert-Contains $gameplayInputShell "private void RegisterActionBarInput()" "Gameplay input shell should own action-bar control registration."
Assert-Contains $gameplayInputShell "DragSession.RegisterTarget(dragAction => ActionBarPresentation.RequestBinding(slot, dragAction));" "Gameplay input shell should wire action-bar drag targets through injected presentation."
Assert-NotContains $actionGameManager "private bool CanOpenRuntimeInputScreen()" "ActionGameManager should not own runtime input-screen availability."
Assert-NotContains $actionGameManager "private void ShowRuntimeInputScreen()" "ActionGameManager should not own runtime input-screen opening."
Assert-NotContains $actionGameManager "Input.Global.InputScreen.performed += context" "ActionGameManager should not own gameplay input callbacks."
Assert-NotContains $actionGameManager "Input.Global.ZoneMap.performed += context" "ActionGameManager should not own gameplay input callbacks."
Assert-NotContains $actionGameManager "Input.Player.TargetNearest.performed += context" "ActionGameManager should not own player targeting callbacks."
Assert-NotContains $actionGameManager "new InputAction(binding: controlPath)" "ActionGameManager should not own action-bar input action construction."
Assert-NotContains $actionGameManager "OnPointerEnterAsObservable()" "ActionGameManager should not own action-bar drag target wiring."
Assert-NotContains $actionGameManager "private void RequestDock()" "ActionGameManager should not keep gameplay request pass-through wrappers."
Assert-NotContains $actionGameManager "private void RequestUndock()" "ActionGameManager should not keep gameplay request pass-through wrappers."
Assert-NotContains $actionGameManager "private void RequestInteract()" "ActionGameManager should not keep gameplay request pass-through wrappers."
Assert-NotContains $actionGameManager "private void RequestTowToStation()" "ActionGameManager should not keep gameplay request pass-through wrappers."
Assert-NotContains $actionGameManager "_towingStation" "ActionGameManager should not cache stale towing context."
Assert-NotContains $actionGameManager "UpdateTowingStation" "ActionGameManager should not receive stale towing context callbacks."
Assert-Contains $actionGameManager "AetheriaUnityObservedRunProjection.FindZone" "ActionGameManager must not own observed galaxy zone lookup logic."
Assert-Contains $actionGameManager "() => AetheriaUnityObservedRunProjection.Galaxy" "ActionGameManager may pass the observed sector projection only into the quarantined zone context adapter."
Assert-NotContains $actionGameManager "private static Galaxy ObservedGalaxy" "ActionGameManager must not keep an observed galaxy property."
Assert-NotContains $actionGameManager "FindObservedGalaxyZone" "ActionGameManager must not own observed galaxy zone lookup logic."
Assert-NotContains $actionGameManager "public static void ProjectObservedDaemonRun(" "ActionGameManager must not own daemon run projection."
Assert-Contains $mainMenu "AetheriaUnityObservedRunProjection.Project(" "MainMenu must project daemon run boot data through the explicit observed-run projection holder."
Assert-NotContains $actionGameManager "public bool CanShowInputScreenFromMenu()" "ActionGameManager must not expose input-screen availability as public manager API."
Assert-NotContains $actionGameManager "public void ShowInputScreenFromMenu()" "ActionGameManager must not expose input-screen opening as public manager API."
Assert-NotContains $actionGameManager "public static Galaxy ObservedGalaxy" "ActionGameManager must not expose the observed galaxy as public gameplay state."
Assert-NotContains $actionGameManager "public static bool IsTutorial" "ActionGameManager must not mirror tutorial mode as public manager-global gameplay state."
Assert-NotContains $actionGameManager "CurrentEnvironment" "ActionGameManager must not expose presentation environment as manager-global gameplay state."
Assert-NotContains $actionGameManager "TryGetObservedGalaxy(out Galaxy galaxy)" "ActionGameManager must not expose broad observed galaxy read shims."
Assert-NotContains $actionGameManager "TryGetObservedZoneSnapshot(" "ActionGameManager must not expose broad observed zone snapshot read shims."
Assert-NotContains $actionGameManager "TryGetObservedRunZone(" "ActionGameManager must not expose broad observed run-zone read shims."
Assert-NotContains $actionGameManager "public EquippedDockingBay DockingBay" "ActionGameManager must not expose renderer-local docking bay state as public gameplay truth."
Assert-NotContains $actionGameManager "public Entity DockedEntity" "ActionGameManager must not expose renderer-local docked entity state as public gameplay truth."
Assert-NotContains $actionGameManager "public Entity TowingStation" "ActionGameManager must not expose renderer-local towing context as public gameplay truth."
Assert-NotContains $actionGameManager "AvailableCargoBays()" "ActionGameManager must not expose renderer-local available cargo bay enumeration."
Assert-NotContains $actionGameManager "public int Credits" "ActionGameManager must not expose manager-global credits."
Assert-NotContains $actionGameManager "Credits = render.Credits" "ActionGameManager must not mirror daemon credits into manager-global state."
Assert-NotContains $actionGameManager "public static AetheriaRuntimeCatalogSnapshot RuntimeCatalog" "ActionGameManager must not expose the runtime catalog as manager-global gameplay state."
Assert-NotContains $actionGameManager "public AetheriaRuntimeCatalogSnapshot RuntimeCatalog" "ActionGameManager must not expose the runtime catalog as manager-global gameplay state."
Assert-NotContains $actionGameManager "ObservedDaemonRenderSettings(" "ActionGameManager must not own daemon render settings lowering."
Assert-NotContains $actionGameManager "new AetheriaRuntimeDaemonRenderSettings(" "ActionGameManager must not construct daemon render settings directly."
Assert-NotContains $actionGameManager "public EntityConstructionBlueprint CreateEntityConstructionBlueprint(AetheriaRuntimeLoadoutTemplateSnapshot template)" "ActionGameManager loadout template lowering must remain private renderer/bootstrap adaptation."
Assert-NotContains $actionGameManager "public static RuntimePlayerSettings RuntimePlayerSettings" "ActionGameManager must not expose player settings as manager-global gameplay state."
Assert-Contains $actionGameManager "AetheriaUnityRuntimeClientProvider.PlayerSettings" "ActionGameManager should read Unity runtime player settings through the runtime client provider."
Assert-Contains $gameplayBootShell "AetheriaUnityRuntimeClientProvider.ResolveClient(stateBoot.StateFilePath, stateBoot.RuntimeId)" "Gameplay boot shell should open typed catalog through the runtime client provider."
Assert-Contains $runtimeClientProvider "public static class AetheriaUnityRuntimeClientProvider" "Unity runtime client cache should live outside ActionGameManager."
Assert-Contains $runtimeClientProvider "public static RuntimePlayerSettings PlayerSettings =>" "Unity runtime client provider should own player settings loading."
Assert-Contains $runtimeClientProvider "public static AetheriaClient ResolveClient(string stateFilePath, string runtimeId = """")" "Unity runtime client provider should own runtime-id-aware typed client caching."
Assert-Contains $runtimeClientProvider "PlayerSettingsAsync()" "Unity runtime client provider should read player settings through AetheriaClient."
Assert-NotContains $actionGameManager "ResolveRuntimeClient(" "ActionGameManager should not own typed client caching."
Assert-NotContains $actionGameManager "PlayerSettingsAsync()" "ActionGameManager should not load player settings directly."
Assert-NotContains $actionGameManager "ApplyRuntimePlayerSettings(" "ActionGameManager should not map player settings snapshots."
Assert-NotContains $actionGameManager "_runtimeClient" "ActionGameManager should not own typed runtime client cache."
Assert-NotContains $actionGameManager "public static DirectoryInfo GameDataDirectory" "ActionGameManager must not expose Unity runtime paths as gameplay state."
Assert-NotContains $actionGameManager "public static string RuntimeStateFilePath" "ActionGameManager must not expose Unity runtime paths as gameplay state."
Assert-NotContains $actionGameManager "ObservedAvailableEntities()" "ActionGameManager must not expose broad observed available entity collections as station/refit truth."
Assert-NotContains $actionGameManager "TryResolveObservedCargoBayCommandTarget" "ActionGameManager must not expose cargo command-target adapters."
Assert-NotContains $actionGameManager "TryResolveObservedEquippedItemCommandTarget" "ActionGameManager must not expose equipment command-target adapters."
Assert-NotContains $actionGameManager "TryResolveCargoBayCommandTarget" "ActionGameManager must not keep private cargo command-target adapters."
Assert-NotContains $actionGameManager "TryResolveEquippedItemCommandTarget" "ActionGameManager must not keep private equipment command-target adapters."
Assert-NotContains $actionGameManager "TryGetObservedDockedLocalStory" "ActionGameManager must not expose docked local-story adapters."
Assert-NotContains $actionGameManager "IsObservedDocked" "ActionGameManager must not expose docked-state read shims."
Assert-NotContains $actionGameManager "TryGetObservedCurrentEntity(" "ActionGameManager must not expose broad current-entity read shims."
Assert-NotContains $actionGameManager "TryGetObservedDockingBay(" "ActionGameManager must not expose broad docking-bay read shims."
Assert-NotContains $actionGameManager "ObservedLoadoutTemplates" "ActionGameManager must not expose loadout templates as manager-global observed state."
Assert-NotContains $actionGameManager "_observedLoadoutTemplates" "ActionGameManager must not cache loadout templates as manager-global observed state."
Assert-NotContains $actionGameManager "LoadRuntimeLoadoutTemplates" "ActionGameManager must not preload loadout templates; clients read typed state directly."
Assert-NotContains $actionGameManager "ProjectLoadoutTemplate(Entity entity)" "ActionGameManager must not own typed loadout projection."
Assert-NotContains $actionGameManager "public DragObject DragObject" "ActionGameManager must not expose raw drag gesture state."
Assert-NotContains $actionGameManager "public bool HasDragTarget" "ActionGameManager must not expose raw drag-target state."
Assert-NotContains $actionGameManager "_dragObject" "ActionGameManager must not own raw drag gesture fields."
Assert-NotContains $actionGameManager "_endDragCallback" "ActionGameManager must not own raw drag-target callback fields."
Assert-Contains $actionGameManager "private readonly AetheriaUnityDragSession _dragSession" "ActionGameManager should delegate drag session state to a helper."
Assert-Contains $actionGameManager "SceneWiring.ConfigureInventoryDragSession(_dragSession)" "ActionGameManager should delegate drag-session UI injection to scene wiring."
Assert-Contains $sceneWiring "Inventory?.SetDragSession(dragSession)" "InventoryMenu should receive the shared drag session explicitly."
Assert-NotContains $actionGameManager "public void BeginDrag(" "ActionGameManager must not expose inventory drag begin as manager API."
Assert-NotContains $actionGameManager "public bool TryGetDraggedItem(" "ActionGameManager must not expose inventory drag queries as manager API."
Assert-NotContains $actionGameManager "public void RegisterDragTarget(" "ActionGameManager must not expose inventory drag target registration as manager API."
Assert-NotContains $actionGameManager "public void UnregisterDragTarget(" "ActionGameManager must not expose inventory drag target clearing as manager API."
Assert-NotContains $actionGameManager "public bool EndDrag(" "ActionGameManager must not expose inventory drag completion as manager API."

$dragSession = Read-Text "Assets\Scripts\Gameplay\AetheriaUnityDragSession.cs"
$dragObjects = Read-Text "Assets\Scripts\Gameplay\AetheriaUnityDragObjects.cs"
Assert-Contains $dragSession "public sealed class AetheriaUnityDragSession" "Inventory drag session state should live outside ActionGameManager."
Assert-Contains $dragSession "private DragObject _dragObject" "Drag session helper should own the raw drag object."
Assert-Contains $dragSession "private Action<DragObject> _endDragCallback" "Drag session helper should own the drop target callback."
Assert-Contains $dragObjects "public abstract class DragObject" "Unity drag payload objects should live outside ActionGameManager."
Assert-Contains $dragObjects "public abstract class ItemDragObject : DragObject" "Unity item drag payload objects should live outside ActionGameManager."
Assert-Contains $dragObjects "public class ItemInstanceDragObject : ItemDragObject" "Unity item-instance drag payload objects should live outside ActionGameManager."
Assert-Contains $dragObjects "public class EquippedItemDragObject : ItemDragObject" "Unity equipped-item drag payload objects should live outside ActionGameManager."
Assert-NotContains $actionGameManager "public abstract class DragObject" "ActionGameManager must not define raw drag payload objects."
Assert-NotContains $actionGameManager "public abstract class ItemDragObject" "ActionGameManager must not define raw drag payload objects."
Assert-NotContains $actionGameManager "public class ItemInstanceDragObject" "ActionGameManager must not define raw drag payload objects."
Assert-NotContains $actionGameManager "public class EquippedItemDragObject" "ActionGameManager must not define raw drag payload objects."

$actionBarSlot = Read-Text "Assets\Scripts\Gameplay\ActionBarSlot.cs"
Assert-Contains $actionBarSlot "protected GameSettings Settings { get; }" "ActionBar bindings should receive presentation settings explicitly."
Assert-Contains $actionBarSlot "Settings.GetIcon(weaponType)" "ActionBar gear icon fallback should use injected presentation settings."
Assert-NotContains $actionBarSlot "ActionGameManager.Instance" "ActionBarSlot must not reach through ActionGameManager.Instance for icon presentation."

$actionBarPresentation = Read-Text "Assets\Scripts\Gameplay\AetheriaUnityActionBarPresentation.cs"
Assert-Contains $actionBarPresentation "public sealed class AetheriaUnityActionBarPresentation" "Action-bar presentation reads should live outside ActionGameManager."
Assert-Contains $actionBarPresentation "public int SlotCount" "Action-bar presentation should expose slot count without manager API."
Assert-Contains $actionBarPresentation "public string SlotLabel(int slotIndex)" "Action-bar presentation should expose slot labels without manager API."
Assert-Contains $actionBarPresentation "public string BindingLabel(int slotIndex)" "Action-bar presentation should expose binding labels without manager API."
Assert-Contains $actionBarPresentation "public bool TryResolveControlPath(int slotIndex, out string controlPath)" "Action-bar presentation should resolve slot control paths without manager API."
Assert-Contains $actionBarPresentation "public bool RequestWeaponGroupBinding(int slotIndex, int groupIndex)" "Action-bar presentation should own local weapon-group binding edits."
Assert-Contains $actionBarPresentation "public bool ClearBinding(int slotIndex)" "Action-bar presentation should own local binding clears."
Assert-Contains $actionBarPresentation "ApplyLocalBindings();" "Action-bar presentation should apply local input mappings directly."
Assert-NotContains $actionBarPresentation "Operations.SetActionBarBinding(" "Action-bar binding edits are Unity-local input maps, not daemon operations."
Assert-NotContains $actionBarPresentation "Operations.ClearActionBarBinding(" "Action-bar binding clears are Unity-local input maps, not daemon operations."
Assert-Contains $actionGameManager "private readonly AetheriaUnityActionBarPresentation _actionBarPresentation" "ActionGameManager should own only the local action-bar presentation wiring."
Assert-Contains $sceneWiring "public void ConfigureActionBarPresentation(" "Scene wiring should inject action-bar presentation into UI shells with explicit boot catalog."
Assert-Contains $sceneWiring "Inventory?.SetActionBarPresentation(actionBarPresentation)" "InventoryMenu should receive action-bar presentation through scene wiring."
Assert-Contains $actionGameManager "ActionBarPresentation = _actionBarPresentation" "ActionGameManager should inject action-bar presentation into the input shell."
Assert-Contains $sceneWiring "gameplayInputShell?.ActionBarSlots" "Scene wiring should bind action-bar presentation to input-shell slots."
Assert-NotContains $actionGameManager "public int GetActionBarSlotCount(" "ActionGameManager must not expose action-bar slot count as public UI API."
Assert-NotContains $actionGameManager "public string GetActionBarSlotLabel(" "ActionGameManager must not expose action-bar slot labels as public UI API."
Assert-NotContains $actionGameManager "public string GetActionBarBindingLabel(" "ActionGameManager must not expose action-bar binding labels as public UI API."
Assert-NotContains $actionGameManager "public bool TryResolveActionBarSlotControlPath(" "ActionGameManager must not expose action-bar control path resolution as public UI API."

$laser = Read-Text "Assets\Scripts\Gameplay\Weapons\Laser.cs"
$constantLaser = Read-Text "Assets\Scripts\Gameplay\Weapons\ConstantLaser.cs"
$hitscanEffect = Read-Text "Assets\Scripts\Gameplay\Weapons\HitscanEffect.cs"
$guidedProjectile = Read-Text "Assets\Scripts\Gameplay\Weapons\GuidedProjectile.cs"
$laserManager = Read-Text "Assets\Scripts\Gameplay\Weapons\LaserManager.cs"
$constantLaserManager = Read-Text "Assets\Scripts\Gameplay\Weapons\ConstantLaserManager.cs"
$hitscanManager = Read-Text "Assets\Scripts\Gameplay\Weapons\HitscanManager.cs"
$guidedProjectileManager = Read-Text "Assets\Scripts\Gameplay\Weapons\GuidedProjectileManager.cs"
Assert-Contains $laser "public ZoneRenderer ZoneRenderer { get; set; }" "Laser effects must receive renderer context explicitly for Ymir queries."
Assert-Contains $constantLaser "public ZoneRenderer ZoneRenderer { get; set; }" "Constant laser effects must receive renderer context explicitly for Ymir queries."
Assert-Contains $hitscanEffect "public ZoneRenderer ZoneRenderer { get; set; }" "Hitscan effects must receive renderer context explicitly for Ymir queries."
Assert-Contains $guidedProjectile "public ZoneRenderer ZoneRenderer { get; set; }" "Guided projectiles must receive renderer context explicitly for Ymir queries."
Assert-Contains $guidedProjectile "child.ZoneRenderer = ZoneRenderer" "Guided projectile children must inherit explicit renderer context."
Assert-Contains $laserManager "p.ZoneRenderer = source.ZoneRenderer" "LaserManager must pass source renderer context to effects."
Assert-Contains $constantLaserManager "p.ZoneRenderer = source.ZoneRenderer" "ConstantLaserManager must pass source renderer context to effects."
Assert-Contains $hitscanManager "p.ZoneRenderer = source.ZoneRenderer" "HitscanManager must pass source renderer context to effects."
Assert-Contains $guidedProjectileManager "p.ZoneRenderer = source.ZoneRenderer" "GuidedProjectileManager must pass source renderer context to effects."
Assert-NotContains $laser "ActionGameManager.Instance" "Laser effects must not reach through ActionGameManager.Instance."
Assert-NotContains $constantLaser "ActionGameManager.Instance" "Constant laser effects must not reach through ActionGameManager.Instance."
Assert-NotContains $hitscanEffect "ActionGameManager.Instance" "Hitscan effects must not reach through ActionGameManager.Instance."
Assert-NotContains $guidedProjectile "ActionGameManager.Instance" "Guided projectiles must not reach through ActionGameManager.Instance."

$client = Read-Text "Packages\org.gamecult.aetheria.state\Runtime\AetheriaClient.cs"
$loadoutProjector = Read-Text "Packages\org.gamecult.aetheria.state\Runtime\AetheriaRuntimeLoadoutSnapshotProjector.cs"
Assert-Contains $loadoutProjector "ProjectLoadoutTemplate(" "Typed loadout projection must live in the shared runtime package."
Assert-Contains $loadoutProjector "AetheriaRuntimeEntitySnapshotCommit entity" "Shared loadout projection must support daemon entity snapshots."
Assert-Contains $client "LoadoutTemplateAsync" "AetheriaClient must expose daemon-backed loadout template projection."

$inventoryPanel = Read-Text "Assets\Scripts\UI\Menu\InventoryPanel.cs"
Assert-NotContains $inventoryPanel "AetheriaRuntimeLoadoutProjector.ProjectLoadoutTemplate(entity)" "InventoryPanel must not save loadouts by serializing Unity entity facades."
Assert-NotContains $inventoryPanel "ActionGameManager.ProjectLoadoutTemplate" "InventoryPanel must not ask ActionGameManager to project typed loadouts."
Assert-Contains $inventoryPanel "public void SetDragSession(AetheriaUnityDragSession dragSession)" "InventoryPanel must receive drag state as an explicit UI dependency."
Assert-Contains $inventoryPanel "DragSession.TryGetDraggedItem(out var itemDragObject)" "InventoryPanel must query item drags through the injected drag session."
Assert-NotContains $inventoryPanel "GameManager.BeginDrag" "InventoryPanel must not route drag begin through ActionGameManager."
Assert-NotContains $inventoryPanel "GameManager.EndDrag" "InventoryPanel must not route drag completion through ActionGameManager."
Assert-NotContains $inventoryPanel "GameManager.TryGetDraggedItem" "InventoryPanel must not query drag state through ActionGameManager."
Assert-NotContains $inventoryPanel "GameManager.RegisterDragTarget" "InventoryPanel must not route drag target registration through ActionGameManager."
Assert-NotContains $inventoryPanel "GameManager.UnregisterDragTarget" "InventoryPanel must not route drag target clearing through ActionGameManager."
Assert-NotContains $inventoryPanel "GameManager.DragObject" "InventoryPanel must not peek raw manager drag state."
Assert-NotContains $inventoryPanel "GameManager.HasDragTarget" "InventoryPanel must not peek raw manager drag-target state."

$runtimePaths = Read-Text "Assets\Scripts\Gameplay\AetheriaUnityRuntimePaths.cs"
Assert-Contains $runtimePaths "public static class AetheriaUnityRuntimePaths" "Unity runtime paths must live outside ActionGameManager."
Assert-Contains $runtimePaths "public static DirectoryInfo GameDataDirectory" "Unity runtime paths must expose the GameData directory through a dedicated helper."
Assert-Contains $runtimePaths "public static string RuntimeStateFilePath" "Unity runtime paths must expose the state file path through a dedicated helper."

$stateDocs = Read-Text "Packages\org.gamecult.aetheria.state\Runtime\AetheriaRuntimeDaemonDocuments.cs"
Assert-Contains $stateDocs "ObjectsViewport" "Daemon schema catalog must advertise objects viewport."
Assert-Contains $stateDocs "GravityViewport" "Daemon schema catalog must advertise gravity viewport."
Assert-Contains $stateDocs "CurrentZone" "Daemon schema catalog must advertise current zone."
Assert-Contains $stateDocs "CurrentEntity" "Daemon schema catalog must advertise current entity."
Assert-Contains $stateDocs "CurrentDocking" "Daemon schema catalog must advertise current docking."
Assert-Contains $stateDocs "ZoneContacts" "Daemon schema catalog must advertise zone contacts."
Assert-Contains $stateDocs "StationRefit" "Daemon schema catalog must advertise station refit."
Assert-Contains $stateDocs "SectorMap" "Daemon schema catalog must advertise sector map."
Assert-Contains $stateDocs "ZoneDetails" "Daemon schema catalog must advertise zone details."
Assert-Contains $stateDocs "ZoneRender" "Daemon schema catalog must advertise zone render feed."

$catalogStore = Read-Text "Packages\org.gamecult.aetheria.state\Runtime\AetheriaRuntimeCatalogStore.cs"
Assert-Contains $catalogStore "ProjectTradeValuePolicySurfaceDocument" "Catalog store must expose typed trade-value policy as a designer Eve surface."
Assert-Contains $catalogStore "AetheriaRuntimeTradeValuePolicySurfaceBuilder.Build" "Catalog store must build trade-value policy through the shared Eve surface builder."

$tradeValuePolicySurface = Read-Text "Packages\org.gamecult.aetheria.state\Runtime\AetheriaRuntimeTradeValuePolicySurfaceBuilder.cs"
Assert-Contains $tradeValuePolicySurface "SurfaceId = ""aetheria.tradeValuePolicy""" "Trade-value policy surface must have a stable designer surface id."
Assert-Contains $tradeValuePolicySurface "Quality Price Modifier" "Trade-value policy surface must expose the quality pricing curve."
Assert-Contains $tradeValuePolicySurface "Rarity Tiers" "Trade-value policy surface must expose rarity tiers."
Assert-Contains $tradeValuePolicySurface "AetheriaRuntimeTradeValuePolicyCommands.SetQualityMinimum" "Trade-value policy surface must expose typed curve edit commands."
Assert-Contains $tradeValuePolicySurface "AetheriaRuntimeTradeValuePolicyCommands.SetTierQuality" "Trade-value policy surface must expose typed tier edit commands."
Assert-Contains $tradeValuePolicySurface "control.text" "Trade-value policy surface must expose editable numeric controls instead of read-only metrics only."

$eveCommandDocument = Read-Text "Packages\org.gamecult.aetheria.state\Runtime\AetheriaRuntimeEveCommandDocument.cs"
Assert-Contains $eveCommandDocument "AetheriaRuntimeTradeValuePolicyCommandBody" "Eve command document must carry a typed trade-value policy command body."
Assert-Contains $eveCommandDocument "SetTradeValueQualityMinimum" "Eve command kinds must include typed trade-value policy edits."

$eveCommandClient = Read-Text "Packages\org.gamecult.aetheria.state\Runtime\AetheriaRuntimeEveCommandClient.cs"
Assert-Contains $eveCommandClient "CreateTradeValuePolicyCommand" "Eve command client must lower trade-value policy surface requests into typed commands."
Assert-Contains $eveCommandClient "ReadTradeValuePolicyBody" "Eve command client must parse trade-value policy payload into a typed body."

$eveCommandBridge = Read-Text "Aetheria.State\AetheriaEveCommandBridge.cs"
Assert-Contains $eveCommandBridge "ExecuteTradeValuePolicyCommandAsync" "Eve command bridge must persist typed trade-value policy edits."
Assert-Contains $eveCommandBridge "PutTradeValuePolicyAsync" "Trade-value policy edits must write the typed policy document."

$tickRunner = Read-Text "Packages\org.gamecult.aetheria.state\Runtime\AetheriaRuntimeDaemonTickRunner.cs"
Assert-Contains $tickRunner "ProjectTradeValuePolicySurfaceDocument(stateFilePath)" "Daemon editor surface must publish the trade-value policy designer surface."

$client = Read-Text "Packages\org.gamecult.aetheria.state\Runtime\AetheriaClient.cs"
Assert-Contains $client "AetheriaClientState State" "AetheriaClient must expose the semantic typed state facade."
Assert-Contains $client "Aetheria()" "AetheriaClient must expose the canonical domain facade entrypoint."
Assert-Contains $client "ObjectsViewportAsync" "AetheriaClient must expose objects viewport facade."
Assert-Contains $client "GravityViewportAsync" "AetheriaClient must expose gravity viewport facade."
Assert-Contains $client "CurrentZoneAsync" "AetheriaClient must expose current-zone facade."
Assert-Contains $client "CurrentEntityAsync" "AetheriaClient must expose current-entity facade."
Assert-Contains $client "CurrentDockingAsync" "AetheriaClient must expose current-docking facade."
Assert-Contains $client "ZoneContactsAsync" "AetheriaClient must expose zone-contacts facade."
Assert-Contains $client "StationRefitAsync" "AetheriaClient must expose station-refit facade."
Assert-Contains $client "SectorMapAsync" "AetheriaClient must expose sector-map facade."
Assert-Contains $client "ZoneDetailsAsync" "AetheriaClient must expose zone-details facade."
Assert-Contains $client "ZoneRenderAsync" "AetheriaClient must expose zone-render facade."

$verseClient = Read-Text "Packages\org.gamecult.aetheria.state\Runtime\AetheriaRuntimeVerseClient.cs"
Assert-Contains $verseClient "AetheriaClientState Aetheria()" "AetheriaRuntimeVerseClient must expose the shared domain state facade."
Assert-Contains $verseClient "CreateAetheriaStateFacade" "AetheriaRuntimeVerseClient must own projected state facade creation."

$clientState = Read-Text "Packages\org.gamecult.aetheria.state\Runtime\AetheriaClientState.cs"
Assert-Contains $clientState "CultMeshBoundLiveFeed" "Aetheria state documents must bind through CultMesh live feeds."
Assert-Contains $clientState "LatestAsync()" "Aetheria state documents must support one-shot typed reads."
Assert-Contains $clientState "Watch()" "Aetheria state documents must support reactive typed reads."

$projection = Read-Text "Packages\org.gamecult.aetheria.state\Runtime\AetheriaRuntimeRtsProjection.cs"
Assert-Contains $projection "ProjectZoneDetails" "Shared projection code must own the zone-details feed."
Assert-Contains $projection "ProjectZoneContacts" "Shared projection code must own the zone-contacts feed."
Assert-Contains $projection "ProjectZoneTargetRow" "Zone-contacts projection must carry target geometry rows."
Assert-Contains $projection "Distance = Math.Sqrt(deltaX * deltaX + deltaZ * deltaZ)" "Zone-contacts projection must carry target/contact distances."
Assert-Contains $projection "ProjectZoneRender" "Shared projection code must own the zone-render feed."
Assert-Contains $projection "ProjectCurrentEntity" "Shared projection code must own the current-entity feed."
Assert-Contains $projection "ProjectCurrentDocking" "Shared projection code must own the current-docking feed."
Assert-Contains $projection "ProjectStationRefit" "Shared projection code must own the station-refit feed."
Assert-Contains $projection "Credits = context.Run.Credits" "Station-refit projection must carry typed run credits."
Assert-Contains $projection "ProjectStationStock" "Station-refit projection must carry typed station stock."
Assert-Contains $projection "CargoItems = ProjectStationStock(entity)" "Station-refit entity options must carry typed cargo rows for target counts."
Assert-Contains $projection "ProjectStationStockTradeFacts" "Station-refit projection must enrich station stock with trade facts."
Assert-Contains $projection "OwnedQuantity = CountStationOwnedQuantity" "Station-refit projection must publish owned counts for trade rows."
Assert-Contains $projection "CanAfford = price >= 0 && credits >= price" "Station-refit projection must publish affordability for trade rows."
Assert-Contains $projection "SourceIndex = sourceIndex" "Inventory projections must carry source slot identity for cargo/equipment operations."
Assert-Contains $projection "X = slot.X" "Inventory projections must carry item grid X for cargo/equipment operations."
Assert-Contains $projection "Y = slot.Y" "Inventory projections must carry item grid Y for cargo/equipment operations."

$zoneRenderDocs = Read-Text "Packages\org.gamecult.aetheria.state\Runtime\AetheriaRuntimeRtsViewportDocuments.cs"
Assert-Contains $zoneRenderDocs "public int SourceIndex" "Inventory item projection documents must carry source index."
Assert-Contains $zoneRenderDocs "public int X" "Inventory item projection documents must carry grid X."
Assert-Contains $zoneRenderDocs "public int Y" "Inventory item projection documents must carry grid Y."
Assert-Contains $zoneRenderDocs "AetheriaRuntimeZoneRenderDocument" "Runtime documents must define the zone-render feed."
Assert-Contains $zoneRenderDocs "AetheriaRuntimeZoneDetailsDocument" "Runtime documents must define the zone-details feed."
Assert-Contains $zoneRenderDocs "public bool IsTutorial" "Sector-map feed must carry tutorial mode for observed Unity boot without whole-frame reads."
Assert-Contains $zoneRenderDocs "public uint GenerationSeed" "Sector-map feed must carry generation seed for observed Unity boot without whole-frame reads."
Assert-Contains $zoneRenderDocs "FactionRelationships" "Sector-map feed must carry faction relationship facts for observed Unity boot without whole-frame reads."
Assert-Contains $zoneRenderDocs "EntityHullItemKeys" "Zone-details feed must carry entity hull identity without exposing whole zone snapshots."
Assert-Contains $zoneRenderDocs "AetheriaRuntimeZoneContactsDocument" "Runtime documents must define the zone-contacts feed."
Assert-Contains $zoneRenderDocs "AetheriaRuntimeZoneContactRow" "Zone-contacts feed must carry typed contact rows."
Assert-Contains $zoneRenderDocs "AetheriaRuntimeZoneTargetRow" "Zone-contacts feed must carry typed target rows."
Assert-Contains $zoneRenderDocs "public double Distance" "Zone-contacts rows must carry target/contact distance."
Assert-Contains $zoneRenderDocs "public double TargetPositionX" "Zone-contacts rows must carry target position."
Assert-Contains $zoneRenderDocs "ZoneRenderRadius" "Zone-render feed must carry render radius as an explicit fact."
Assert-Contains $zoneRenderDocs "AdjacentZones" "Zone-render feed must carry adjacent-zone summaries for renderer wormholes."
Assert-Contains $zoneRenderDocs "WormholeExits" "Zone-render feed must carry resolved wormhole exits as explicit render facts."
Assert-Contains $zoneRenderDocs "BodyPoses" "Zone-render feed must carry body poses as explicit render facts."
Assert-Contains $zoneRenderDocs "AsteroidBeltPoses" "Zone-render feed must carry asteroid belt poses as explicit render facts."
Assert-Contains $zoneRenderDocs "AetheriaRuntimeZoneRenderAsteroidInstancePose" "Zone-render feed must carry typed asteroid instance poses."
Assert-Contains $zoneRenderDocs "DroppedPickups" "Zone-render feed must carry dropped pickups as explicit render facts."
Assert-Contains $zoneRenderDocs "EntityFacades" "Zone-render feed must carry typed entity facade payloads for Unity shell restoration."
Assert-Contains $zoneRenderDocs "public IReadOnlyList<AetheriaRuntimeOrbitSnapshotCommit> Orbits" "Zone-render feed must carry typed orbit rows for Unity zone context lowering."
Assert-Contains $zoneRenderDocs "public IReadOnlyList<AetheriaRuntimeBodySnapshotCommit> Bodies" "Zone-render feed must carry typed body rows for Unity zone context lowering."
Assert-NotContains $zoneRenderDocs "public AetheriaRuntimeRunCheckpointCommit Run" "Zone-render feed must not expose the whole daemon run snapshot."
Assert-NotContains $zoneRenderDocs "public AetheriaRuntimeZoneSnapshotCommit Zone" "Zone-render feed must not expose the whole daemon zone snapshot."

$zoneRenderer = Read-Text "Assets\Scripts\Zone Display\ZoneRenderer.cs"
Assert-Contains $zoneRenderer "ApplyZoneRender" "ZoneRenderer must consume the typed zone-render feed."
Assert-Contains $zoneRenderer "_daemonCurrentEntityKey" "ZoneRenderer must track current entity as a render-feed fact, not through a run snapshot."
Assert-Contains $zoneRenderer "_daemonSimulationTimeSeconds" "ZoneRenderer must track simulation time as a render-feed fact."
Assert-Contains $zoneRenderer "_zoneRenderBodyPoses" "ZoneRenderer must consume body poses from the zone-render feed."
Assert-Contains $zoneRenderer "_zoneRenderAsteroidBeltPoses" "ZoneRenderer must consume asteroid belt poses from the zone-render feed."
Assert-Contains $zoneRenderer "beltPose.InstancePoses" "ZoneRenderer asteroid rendering must consume typed asteroid instance poses from the zone-render feed."
Assert-Contains $zoneRenderer "RestoreDroppedPickupsFromZoneRender" "ZoneRenderer dropped-pickup restore must consume the typed zone-render feed."
Assert-Contains $zoneRenderer "ZoneContactsAsync()" "ZoneRenderer target distance cache must read the typed zone-contacts feed."
Assert-Contains $zoneRenderer "_daemonTargetRowsByEntityIndex" "ZoneRenderer target distance cache must store typed target rows."
Assert-Contains $zoneRenderer "_daemonContactRows" "ZoneRenderer compass and visibility state must cache typed contact rows."
Assert-Contains $zoneRenderer "ObjectsViewportAsync(ToViewportBounds(viewport))" "ZoneRenderer presentation loading must use the typed objects viewport facade."
Assert-Contains $zoneRenderer "GravityViewportAsync(viewport)" "ZoneRenderer body view loading must use the typed gravity viewport facade."
Assert-Contains $zoneRenderDocs "public AetheriaRuntimeBodySnapshotCommit Body" "Gravity/body viewport rows must carry the typed body payload needed for Unity presentation lowering."
Assert-Contains $zoneRenderDocs "public double TerrainRadius" "Gravity viewport rows must carry terrain radius for local renderer height sampling."
Assert-Contains $zoneRenderDocs "public double TerrainDepth" "Gravity viewport rows must carry terrain depth for local renderer height sampling."
Assert-Contains $zoneRenderDocs "public double TerrainDepthExponent" "Gravity viewport rows must carry terrain exponent for local renderer height sampling."
Assert-Contains $zoneRenderDocs "public double TerrainWaveFrequency" "Gravity viewport rows must carry wave frequency for local renderer height sampling."
Assert-Contains $zoneRenderer "_daemonGravityViewport" "ZoneRenderer terrain sampling must use the cached typed gravity viewport."
Assert-Contains $zoneRenderer "ZoneRenderRadius" "ZoneRenderer must consume render radius from the zone-render feed."
Assert-NotContains $zoneRenderer "_daemonRunSnapshot" "ZoneRenderer must not retain the whole daemon run snapshot."
Assert-NotContains $zoneRenderer "_daemonZoneSnapshot" "ZoneRenderer must not retain the whole daemon zone snapshot."
Assert-NotContains $zoneRenderer "ResolveZoneRenderRadius(" "ZoneRenderer must not derive render radius from the zone snapshot."
Assert-NotContains $zoneRenderer "QueryBodyPoses(" "ZoneRenderer must not recompute body poses from the zone snapshot."
Assert-NotContains $zoneRenderer "QueryBodyViews(" "ZoneRenderer must not compute visible body views from raw zone snapshots."
Assert-NotContains $zoneRenderer "QueryAsteroidBeltPoses(" "ZoneRenderer must not recompute asteroid belt poses from the zone snapshot."
Assert-NotContains $zoneRenderer "QueryAsteroidInstancePoses(" "ZoneRenderer must not recompute asteroid instance poses from the zone snapshot."
Assert-NotContains $zoneRenderer "AetheriaRuntimeDaemonRenderQueries.EvaluateGravityTerrainHeight" "ZoneRenderer must not sample gravity terrain height from raw zone snapshots."
Assert-NotContains $zoneRenderer "AetheriaRuntimeDaemonRenderQueries.QueryGravityTerrainBand" "ZoneRenderer must not compute gravity terrain bands from raw zone snapshots."
Assert-NotContains $zoneRenderer "TryQueryEntityTarget(" "ZoneRenderer must not query target distances from raw zone snapshots."
Assert-NotContains $zoneRenderer "QueryCompassMarkers(" "ZoneRenderer must not recompute compass markers from raw zone snapshots."
Assert-NotContains $zoneRenderer "QueryVisibleEntityIndices(" "ZoneRenderer must not recompute visible entity indices from raw zone snapshots."
Assert-NotContains $zoneRenderer "QueryPresentationEntityIndices(" "ZoneRenderer must not compute presentation entity loading from raw zone snapshots."

$actionGameManager = Read-Text "Assets\Scripts\Gameplay\ActionGameManager.cs"
$observedFrameApplier = Read-Text "Assets\Scripts\Gameplay\AetheriaUnityObservedFrameApplier.cs"
$gameplayLoopShell = Read-Text "Assets\Scripts\Gameplay\AetheriaUnityGameplayLoopShell.cs"
Assert-Contains $actionGameManager "ObservedFrameApplier.ApplyLatestZoneRender()" "ActionGameManager must delegate typed zone-render application to the observed frame applier."
Assert-Contains $actionGameManager "private AetheriaUnityGameplayLoopShell GameplayLoopShell =>" "ActionGameManager should delegate per-frame Unity presentation/input ticking to the gameplay loop shell."
Assert-Contains $actionGameManager "GameplayLoopShell.Tick(Time.deltaTime, Time.time)" "ActionGameManager Update should only forward time into the gameplay loop shell."
Assert-Contains $actionGameManager "GameplayLoopShell.LateTick()" "ActionGameManager LateUpdate should only forward into the gameplay loop shell."
Assert-Contains $gameplayLoopShell "public sealed class AetheriaUnityGameplayLoopShell" "Unity gameplay loop presentation ticking should live outside ActionGameManager."
Assert-Contains $gameplayLoopShell "ApplyLatestZoneRender?.Invoke();" "Gameplay loop shell should apply the latest typed zone-render feed."
Assert-Contains $gameplayLoopShell "CurrentEntityPresentation?.Tick(deltaTime);" "Gameplay loop shell should tick current-entity presentation."
Assert-Contains $gameplayLoopShell "PilotFrameAdapter?.Tick(ResolveCurrentEntity?.Invoke(), deltaTime, time);" "Gameplay loop shell should tick pilot frame presentation/input."
Assert-Contains $gameplayLoopShell "TargetPresentation?.UpdateTargetIndicators(" "Gameplay loop shell should tick target indicators."
Assert-NotContains $actionGameManager "_currentEntityPresentation.Tick(Time.deltaTime);" "ActionGameManager must not tick current-entity presentation directly."
Assert-NotContains $actionGameManager "PilotFrameAdapter.Tick(CurrentEntity, Time.deltaTime, Time.time)" "ActionGameManager must not tick pilot frame presentation/input directly."
Assert-NotContains $actionGameManager "_targetPresentation.UpdateTargetIndicators(" "ActionGameManager must not tick target indicators directly."
Assert-NotContains $actionGameManager "_paused" "ActionGameManager must not own pause state; the loop shell owns it."
Assert-NotContains $actionGameManager "_time" "ActionGameManager must not keep unused local simulation time."
Assert-Contains $observedFrameApplier "TryRestoreEntityGraphFromZoneRender" "Observed frame applier must restore Unity shell state from the typed zone-render feed."
Assert-Contains $observedFrameApplier "ApplyLatestZoneRender" "Observed frame applier must name the handoff as zone-render application."
Assert-Contains $observedFrameApplier "ZoneRenderAsync()" "Observed frame applier must use the shared zone-render facade at the frame handoff."
Assert-Contains $observedFrameApplier "render.EntityFacades" "Observed frame applier entity restoration must consume the typed zone-render entity facade payload."
Assert-NotContains $observedFrameApplier "Func<Galaxy>" "Observed frame applier must not depend on the whole observed galaxy facade."
Assert-Contains $observedFrameApplier "_resolveObservedZone" "Observed frame applier should name the narrow target-zone resolver explicitly."
Assert-NotContains $observedFrameApplier "resolveObservedGalaxy" "Observed frame applier must resolve only the target zone needed for Unity shell adaptation."
Assert-NotContains $observedFrameApplier "render?.Zone" "Observed frame applier must not reach through zone-render into a whole zone snapshot."
Assert-NotContains $observedFrameApplier "ApplyLatestAuthoritativeDaemonFrame" "Observed frame applier must not describe zone-render application as whole daemon frame application."
Assert-NotContains $observedFrameApplier "Authoritative daemon frame" "Observed frame applier diagnostics must describe the typed zone-render feed, not a whole daemon frame."
Assert-NotContains $gameplayLoopShell "ApplyLatestAuthoritativeDaemonFrame" "Gameplay loop shell must not describe zone-render application as whole daemon frame application."
Assert-NotContains $actionGameManager "TryRestoreEntityGraphFromDaemonRun" "ActionGameManager must not restore Unity shell state directly from raw daemon runs."
Assert-NotMatches $actionGameManager "render\.Run(?!Id\b)" "ActionGameManager must not reach through zone-render into a whole run snapshot."
Assert-NotContains $actionGameManager "StampDaemonZoneSimulationTime" "ActionGameManager must not mutate zone snapshots to carry render timing."

Write-Host "Stage 7D Unity parity verifier passed."
